### ISSUE TITLE
Bootstrap non compatible

### ISSUE THREAD

**Issue by leshadubenyuk** [Sweefty/moaModal#1]
Problem when using with bootstrap, cause class with name 'modal' is uses in bootstrap.

**Comment by mamod** [comment]
@leshadubenyuk moaModal doesn't use classes internally only the example use the modal class for demonstration , so you can change that, please try and let me know, thanks.

**Comment by leshadubenyuk** [comment]
@mamod you were right, and it's all good with using another name class. Thanks for your help!
